$(document).ready(function (){
  $('.modelo1').hide();
  $('.capa-1').hide();
  $('.modelo2').hide();
  $('.capa-2').hide();
  $('.modelo3').hide();
  $('.capa-3').hide();
  $('.modelo4').hide();
  $('.capa-4').hide();

  $('.red').click(function(){
  $('#capa').removeClass()
  $('.modelo2').fadeOut();
  $('.capa-2').fadeOut();
  $('.modelo3').fadeOut();
  $('.capa-3').fadeOut();
  $('.modelo4').fadeOut();
  $('.capa-4').fadeOut();
  $('.modelo1').fadeIn('slow');
  $('#capa').addClass('capa-1').fadeIn('slow');
 });
  $('.yellow').click(function(){
  $('#capa').removeClass();
  $('.modelo1').fadeOut();
  $('.capa-1').fadeOut();
  $('.modelo3').fadeOut();
  $('.capa-3').fadeOut();
  $('.modelo4').fadeOut();
  $('.capa-4').fadeOut();
  $('.modelo2').fadeIn('slow');
  $('#capa').addClass('capa-2').fadeIn('slow');
 });
  $('.green').click(function(){
  $('#capa').removeClass();
  $('.modelo2').fadeOut();
  $('.capa-2').fadeOut();
  $('.modelo1').fadeOut();
  $('.capa-1').fadeOut();
  $('.modelo4').fadeOut();
  $('.capa-4').fadeOut();
  $('.modelo3').fadeIn('slow');
  $('#capa').addClass('capa-3').fadeIn('slow');
 });
  $('.blue').click(function(){
  $('#capa').removeClass();
  $('.modelo2').fadeOut();
  $('.capa-2').fadeOut();
  $('.modelo3').fadeOut();
  $('.capa-3').fadeOut();
  $('.modelo1').fadeOut();
  $('.capa-1').fadeOut();
  $('.modelo4').fadeIn('slow');
  $('#capa').addClass('capa-4').fadeIn('slow');
 });
 
 $('a.over-show').click(function(){
	$('#menu li:hover>ul').slideDown('slow');
 })
});
/*
  $('.modelo2').hide();
  $('.capa-2').hide();
  $('.modelo3').hide();
  $('.capa-3').hide();
  $('.modelo4').hide();
  $('.capa-4').hide();
  $('.capa-1').fadeIn('slow');
  $('.modelo1').fadeIn('slow');
 */